module sit.wt.runtime {
  requires java.xml;
  requires jdk.unsupported;
  requires java.sql;
  requires java.naming;
  requires java.desktop;
  requires java.management;
  requires java.security.jgss;
  requires java.instrument;
  requires java.annotation;
  requires spring.context;
  requires spring.core;
  requires spring.beans;
  requires spring.expression;
  requires lombok;
  requires commons.io;
  requires commons.lang3;
  requires selenium.java;
  requires selenium.support;
  requires logback.core;
  requires slf4j.api;
  requires junit;
  requires java.client;
  requires spring.test;
  requires com.fasterxml.jackson.core;
  requires com.fasterxml.jackson.databind;
  requires jackson.annotations;
  requires sit.wt.util;
}
